@echo off
echo ========================================
echo AI Employee Complete System v4.0
echo Gmail + LinkedIn + Twitter API Integration
echo ========================================

echo Starting Gmail Watcher...
start "Gmail Watcher" cmd /k "python simple_gmail_watcher.py"

timeout /t 2 /nobreak >nul

echo Starting Email Response Sender...
start "Email Sender" cmd /k "python email_response_sender.py"

timeout /t 2 /nobreak >nul

echo Starting LinkedIn Automation...
start "LinkedIn Automation" cmd /k "python linkedin_automation.py"

timeout /t 2 /nobreak >nul

echo Starting LinkedIn Content Handler...
start "LinkedIn Handler" cmd /k "python linkedin_content_handler.py"

timeout /t 2 /nobreak >nul

echo Starting Twitter API Handler...
start "Twitter API Handler" cmd /k "python twitter_api_handler.py"

timeout /t 3 /nobreak >nul

echo Starting System Monitor...
start "System Monitor" powershell -Command "while($true) { Clear-Host; Write-Host '=== AI EMPLOYEE SYSTEM v4.0 ===' -ForegroundColor Green; Write-Host ''; Write-Host 'INBOX:' -ForegroundColor Cyan; Get-ChildItem 'AI_Employee_Vault\Inbox' -ErrorAction SilentlyContinue | Select-Object Name, LastWriteTime; Write-Host ''; Write-Host 'NEEDS ACTION:' -ForegroundColor Yellow; Get-ChildItem 'AI_Employee_Vault\Needs_Action' -ErrorAction SilentlyContinue | Select-Object Name, LastWriteTime; Write-Host ''; Write-Host 'DONE (Pending):' -ForegroundColor Blue; Get-ChildItem 'AI_Employee_Vault\Done' -ErrorAction SilentlyContinue | Select-Object Name, LastWriteTime; Write-Host ''; Write-Host 'ARCHIVE (Sent):' -ForegroundColor Gray; Get-ChildItem 'AI_Employee_Vault\Archive' -ErrorAction SilentlyContinue | Select-Object Name, LastWriteTime; Write-Host ''; Write-Host 'TWITTER ANALYTICS:' -ForegroundColor Magenta; Get-ChildItem 'AI_Employee_Vault\Twitter_Analytics' -ErrorAction SilentlyContinue | Select-Object Name, LastWriteTime; Start-Sleep 5 }"

echo ========================================
echo AI Employee System v4.0 Started!
echo ========================================
echo.
echo ACTIVE COMPONENTS:
echo [1] Gmail Watcher: naheadj@gmail.com monitoring
echo [2] Email Response Sender: SMTP automation
echo [3] LinkedIn Automation: Content generation
echo [4] LinkedIn Content Handler: Post publishing
echo [5] Twitter API Handler: Official API posting
echo [6] System Monitor: Real-time vault status
echo.
echo MULTI-PLATFORM CAPABILITIES:
echo - Email automation (87%% time savings)
echo - LinkedIn lead generation (90%% time savings)
echo - Twitter API posting (95%% time savings)
echo - Professional content creation
echo - Human approval workflows
echo - Complete audit trails
echo.
echo TESTING:
echo - Send email to: naheadj@gmail.com
echo - LinkedIn posts auto-generated hourly
echo - Twitter content generated by time
echo - Approve content in /Needs_Action folder
echo - Monitor analytics across all platforms
echo.
echo TWITTER API STATUS:
echo - No browser automation required
echo - Official Twitter API integration
echo - Higher reliability and rate limits
echo - Advanced analytics and scheduling
echo.
pause