#!/usr/bin/env python3
"""
Plan Generator - Silver Tier Requirement
Claude reasoning loop that creates Plan.md files for complex tasks
"""

import os
from pathlib import Path
from datetime import datetime

# Configuration
VAULT_PATH = Path(__file__).parent / "AI_Employee_Vault"
NEEDS_ACTION_FOLDER = VAULT_PATH / "Needs_Action"
PLANS_FOLDER = VAULT_PATH / "Plans"

class PlanGenerator:
    """Generate Plan.md files for complex tasks"""

    def __init__(self):
        self.vault_path = VAULT_PATH
        self.needs_action = NEEDS_ACTION_FOLDER
        self.plans_folder = PLANS_FOLDER
        self.plans_folder.mkdir(exist_ok=True)

    def analyze_task(self, task_file):
        """Analyze task and determine if it needs a plan"""
        content = task_file.read_text(encoding='utf-8')

        # Check if task is complex enough to need a plan
        # Complex tasks typically have:
        # - Multiple steps
        # - Dependencies
        # - External integrations
        # - Approval requirements

        keywords = ['urgent', 'complex', 'multiple', 'integrate', 'approval', 'critical']
        is_complex = any(keyword in content.lower() for keyword in keywords)

        return is_complex

    def create_plan(self, task_file):
        """Create a Plan.md file for a task"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        task_name = task_file.stem
        plan_filename = f"PLAN_{task_name}_{timestamp}.md"
        plan_filepath = self.plans_folder / plan_filename

        # Read task content
        task_content = task_file.read_text(encoding='utf-8')

        # Generate plan structure
        plan_content = f"""---
type: execution_plan
task: {task_name}
created: {datetime.now().isoformat()}
status: draft
---

# Execution Plan: {task_name}

## Task Overview
Source: {task_file.name}
Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Original Task
{task_content}

## Analysis
This task requires a structured approach with multiple steps and considerations.

## Execution Steps

### Phase 1: Preparation
1. **Gather Information**
   - Review all task requirements
   - Identify dependencies
   - Check available resources

2. **Risk Assessment**
   - Identify potential blockers
   - Plan mitigation strategies
   - Set up fallback options

### Phase 2: Execution
1. **Initial Actions**
   - Start with highest priority items
   - Follow approval workflows
   - Document progress

2. **Integration Points**
   - Coordinate with external systems
   - Verify data flow
   - Test connections

### Phase 3: Validation
1. **Quality Checks**
   - Verify all requirements met
   - Test functionality
   - Review with stakeholders

2. **Documentation**
   - Update logs
   - Create completion report
   - Archive relevant files

## Dependencies
- [ ] Required approvals obtained
- [ ] External systems available
- [ ] Resources allocated
- [ ] Stakeholders notified

## Success Criteria
- All task requirements completed
- Quality standards met
- Documentation updated
- Stakeholders satisfied

## Timeline
- **Start:** {datetime.now().strftime('%Y-%m-%d')}
- **Estimated Completion:** TBD based on complexity
- **Review Points:** After each phase

## Notes
- This plan should be reviewed and adjusted as needed
- All changes require approval per company policy
- Regular status updates to be provided

## Next Actions
1. Review this plan
2. Get necessary approvals
3. Begin Phase 1 execution
4. Update plan as progress is made

---
*Generated by AI Employee Planning System*
*Last Updated: {datetime.now().isoformat()}*
"""

        # Write plan file
        with open(plan_filepath, 'w', encoding='utf-8') as f:
            f.write(plan_content)

        print(f"[OK] Created plan: {plan_filename}")
        return plan_filepath

    def process_needs_action(self):
        """Process all tasks in Needs_Action folder"""
        if not self.needs_action.exists():
            print(f"[WARN] Needs_Action folder not found")
            return

        # Find all task files
        task_files = list(self.needs_action.glob("*.md"))

        if not task_files:
            print("[INFO] No tasks found in Needs_Action")
            return

        print(f"[SCAN] Found {len(task_files)} task(s) in Needs_Action")

        plans_created = 0
        for task_file in task_files:
            print(f"\n[ANALYZE] {task_file.name}")

            # Check if task needs a plan
            if self.analyze_task(task_file):
                print(f"[COMPLEX] Task requires execution plan")
                self.create_plan(task_file)
                plans_created += 1
            else:
                print(f"[SIMPLE] Task is straightforward, no plan needed")

        print(f"\n[SUMMARY] Created {plans_created} execution plan(s)")

    def create_sample_plan(self):
        """Create a sample plan for demonstration"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        plan_filename = f"PLAN_SAMPLE_BUSINESS_AUTOMATION_{timestamp}.md"
        plan_filepath = self.plans_folder / plan_filename

        sample_plan = f"""---
type: execution_plan
task: business_automation_implementation
created: {datetime.now().isoformat()}
status: draft
priority: high
---

# Execution Plan: Business Automation Implementation

## Objective
Implement comprehensive business automation system to reduce manual work by 80% and improve response times.

## Current State Analysis
- Manual email responses taking 2-3 hours daily
- LinkedIn posting inconsistent (2-3 times per week)
- No automated client follow-up system
- WhatsApp messages handled reactively

## Target State
- Automated email triage and draft responses
- Daily LinkedIn content generation and posting
- Automated client follow-up workflows
- WhatsApp monitoring with action creation

## Execution Phases

### Phase 1: Foundation (Week 1)
**Goal:** Set up core infrastructure

1. **Vault Structure**
   - ✅ Create folder hierarchy
   - ✅ Set up .gitignore for secrets
   - ✅ Initialize Obsidian vault

2. **Watcher Scripts**
   - ✅ Gmail watcher implementation
   - ✅ WhatsApp watcher setup
   - [ ] File system monitoring

3. **Agent Skills**
   - ✅ Email processor skill
   - ✅ LinkedIn manager skill
   - ✅ WhatsApp handler skill

### Phase 2: Automation (Week 2)
**Goal:** Implement core automation workflows

1. **Email Automation**
   - [ ] Set up IMAP monitoring
   - [ ] Implement draft generation
   - [ ] Create approval workflow
   - [ ] Test email sending via MCP

2. **LinkedIn Automation**
   - ✅ Content generator script
   - ✅ Playwright poster implementation
   - [ ] Schedule daily posting
   - [ ] Track engagement metrics

3. **WhatsApp Integration**
   - ✅ Message monitoring
   - [ ] Response templates
   - [ ] Approval workflow
   - [ ] Session management

### Phase 3: Integration (Week 3)
**Goal:** Connect all systems

1. **MCP Servers**
   - [ ] Email MCP server
   - [ ] Social media MCP server
   - [ ] Task management MCP server

2. **Approval Workflows**
   - [ ] Human-in-the-loop gates
   - [ ] Notification system
   - [ ] Approval tracking

3. **Scheduling**
   - [ ] Windows Task Scheduler setup
   - [ ] Cron jobs for Linux
   - [ ] Health monitoring

### Phase 4: Testing & Optimization (Week 4)
**Goal:** Validate and optimize

1. **Testing**
   - [ ] End-to-end workflow tests
   - [ ] Error handling validation
   - [ ] Performance benchmarks

2. **Documentation**
   - [ ] User guides
   - [ ] API documentation
   - [ ] Troubleshooting guides

3. **Optimization**
   - [ ] Response time improvements
   - [ ] Resource usage optimization
   - [ ] Workflow refinements

## Dependencies & Requirements

### Technical
- [x] Python 3.13+
- [x] Playwright installed
- [x] Claude Code CLI
- [x] Obsidian vault
- [ ] MCP servers configured
- [ ] Task scheduler access

### Credentials
- [x] Gmail SMTP credentials
- [x] LinkedIn login credentials
- [ ] WhatsApp session
- [ ] API keys for integrations

### Approvals
- [ ] Budget approval for cloud hosting
- [ ] Security review for automation
- [ ] Stakeholder sign-off on workflows

## Risk Management

### High Risk
1. **LinkedIn Account Suspension**
   - Mitigation: Use session management, respect rate limits
   - Fallback: Manual posting with generated content

2. **Email Delivery Issues**
   - Mitigation: Test with multiple providers
   - Fallback: Use Resend API instead of SMTP

3. **Data Loss**
   - Mitigation: Git-based vault sync, regular backups
   - Fallback: Cloud backup service

### Medium Risk
1. **API Rate Limits**
   - Mitigation: Implement exponential backoff
   - Monitoring: Track API usage

2. **Session Expiration**
   - Mitigation: Automatic re-authentication
   - Monitoring: Session health checks

## Success Metrics

### Quantitative
- Email response time: < 5 minutes (from 2-3 hours)
- LinkedIn posting: 7 posts/week (from 2-3)
- Manual work reduction: 80%
- System uptime: > 99%

### Qualitative
- Improved client satisfaction
- Consistent brand presence
- Reduced stress from manual tasks
- Better work-life balance

## Timeline

| Phase | Duration | Start Date | End Date | Status |
|-------|----------|------------|----------|--------|
| Phase 1 | 1 week | {datetime.now().strftime('%Y-%m-%d')} | TBD | In Progress |
| Phase 2 | 1 week | TBD | TBD | Pending |
| Phase 3 | 1 week | TBD | TBD | Pending |
| Phase 4 | 1 week | TBD | TBD | Pending |

## Next Actions

### Immediate (Today)
1. ✅ Create plan document
2. [ ] Review with stakeholders
3. [ ] Get approval to proceed
4. [ ] Set up project tracking

### This Week
1. [ ] Complete Phase 1 tasks
2. [ ] Test watcher scripts
3. [ ] Validate agent skills
4. [ ] Begin Phase 2 planning

### This Month
1. [ ] Complete all 4 phases
2. [ ] Full system testing
3. [ ] Documentation complete
4. [ ] Launch automation system

## Notes & Considerations

- All automation requires human approval for sensitive actions
- Security is paramount - no credentials in git
- Start small, iterate quickly
- Document everything for future reference
- Regular check-ins with stakeholders

## Resources

### Documentation
- Silver Tier Requirements: See hackathon document
- Agent Skills Guide: .claude/skills/README.md
- MCP Server Docs: mcp-*/README.md

### Support
- Claude Code: https://claude.ai/code
- Playwright: https://playwright.dev
- Obsidian: https://obsidian.md

---
*This is a living document - update as progress is made*
*Last Updated: {datetime.now().isoformat()}*
*Status: Draft - Awaiting Approval*
"""

        # Write sample plan
        with open(plan_filepath, 'w', encoding='utf-8') as f:
            f.write(sample_plan)

        print(f"[OK] Created sample plan: {plan_filename}")
        return plan_filepath

def main():
    """Main entry point"""
    print("="*70)
    print("PLAN GENERATOR - SILVER TIER")
    print("="*70)

    generator = PlanGenerator()

    # Check command line arguments
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "sample":
        # Create sample plan
        print("\n[MODE] Creating sample execution plan...")
        generator.create_sample_plan()
    else:
        # Process Needs_Action folder
        print("\n[MODE] Processing Needs_Action folder...")
        generator.process_needs_action()

    print("\n" + "="*70)
    print("[DONE] Plan generation complete")
    print("="*70)

if __name__ == "__main__":
    main()
